/* eslint-disable */
// This file is auto-generated by scripts/generate_manifest.mjs

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export interface EndpointPathParam {
  paramName: string;
  token: string;
}

export interface EndpointDescriptor {
  resource: string;
  methodName: string;
  httpMethod: HttpMethod;
  path: string;
  pathParams: EndpointPathParam[];
  summary: string;
}

export const RESOURCE_KEYS = [
  "attachments",
  "backups",
  "chats",
  "contacts",
  "fcm",
  "handles",
  "icloud",
  "macos",
  "messages",
  "server",
  "web"
] as const;
export type ResourceKey = (typeof RESOURCE_KEYS)[number];

export const ENDPOINTS: readonly EndpointDescriptor[] = [
  {
    "resource": "attachments",
    "methodName": "get",
    "httpMethod": "GET",
    "path": "/api/v1/attachment/<GUID>",
    "pathParams": [
      {
        "paramName": "guid",
        "token": "<GUID>"
      }
    ],
    "summary": "Get Attachment by GUID"
  },
  {
    "resource": "attachments",
    "methodName": "blurhash",
    "httpMethod": "GET",
    "path": "/api/v1/attachment/<GUID>/blurhash",
    "pathParams": [
      {
        "paramName": "guid",
        "token": "<GUID>"
      }
    ],
    "summary": "Get Attachment Blurhash"
  },
  {
    "resource": "attachments",
    "methodName": "download",
    "httpMethod": "GET",
    "path": "/api/v1/attachment/<GUID>/download",
    "pathParams": [
      {
        "paramName": "guid",
        "token": "<GUID>"
      }
    ],
    "summary": "Download Attachment"
  },
  {
    "resource": "attachments",
    "methodName": "downloadForce",
    "httpMethod": "GET",
    "path": "/api/v1/attachment/<GUID>/download/force",
    "pathParams": [
      {
        "paramName": "guid",
        "token": "<GUID>"
      }
    ],
    "summary": "Force Download Attachment"
  },
  {
    "resource": "attachments",
    "methodName": "livePhoto",
    "httpMethod": "GET",
    "path": "/api/v1/attachment/<GUID>/live",
    "pathParams": [
      {
        "paramName": "guid",
        "token": "<GUID>"
      }
    ],
    "summary": "Get Attachment Live Photo"
  },
  {
    "resource": "attachments",
    "methodName": "count",
    "httpMethod": "GET",
    "path": "/api/v1/attachment/count",
    "pathParams": [],
    "summary": "Get Attachment Count"
  },
  {
    "resource": "attachments",
    "methodName": "upload",
    "httpMethod": "POST",
    "path": "/api/v1/attachment/upload",
    "pathParams": [],
    "summary": "Upload Attachment"
  },
  {
    "resource": "backups",
    "methodName": "getSettings",
    "httpMethod": "GET",
    "path": "/api/v1/backup/settings",
    "pathParams": [],
    "summary": "Get Settings"
  },
  {
    "resource": "backups",
    "methodName": "saveSettings",
    "httpMethod": "POST",
    "path": "/api/v1/backup/settings",
    "pathParams": [],
    "summary": "Save Settings"
  },
  {
    "resource": "backups",
    "methodName": "deleteSettings",
    "httpMethod": "DELETE",
    "path": "/api/v1/backup/settings",
    "pathParams": [],
    "summary": "Delete Settings"
  },
  {
    "resource": "backups",
    "methodName": "listThemes",
    "httpMethod": "GET",
    "path": "/api/v1/backup/theme",
    "pathParams": [],
    "summary": "Get Themes"
  },
  {
    "resource": "backups",
    "methodName": "saveTheme",
    "httpMethod": "POST",
    "path": "/api/v1/backup/theme",
    "pathParams": [],
    "summary": "Save Theme"
  },
  {
    "resource": "backups",
    "methodName": "deleteTheme",
    "httpMethod": "DELETE",
    "path": "/api/v1/backup/theme",
    "pathParams": [],
    "summary": "Delete Theme"
  },
  {
    "resource": "chats",
    "methodName": "get",
    "httpMethod": "GET",
    "path": "/api/v1/chat/<Chat GUID>",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Get Chat Icon by GUID"
  },
  {
    "resource": "chats",
    "methodName": "update",
    "httpMethod": "PUT",
    "path": "/api/v1/chat/<Chat GUID>",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Update a Chat"
  },
  {
    "resource": "chats",
    "methodName": "delete",
    "httpMethod": "DELETE",
    "path": "/api/v1/chat/<Chat GUID>",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Delete Chat"
  },
  {
    "resource": "chats",
    "methodName": "setIcon",
    "httpMethod": "POST",
    "path": "/api/v1/chat/<Chat GUID>/icon",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Set Group Icon"
  },
  {
    "resource": "chats",
    "methodName": "removeIcon",
    "httpMethod": "DELETE",
    "path": "/api/v1/chat/<Chat GUID>/icon",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Remove Group Icon"
  },
  {
    "resource": "chats",
    "methodName": "leave",
    "httpMethod": "POST",
    "path": "/api/v1/chat/<Chat GUID>/leave",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Leave Chat"
  },
  {
    "resource": "chats",
    "methodName": "listMessages",
    "httpMethod": "GET",
    "path": "/api/v1/chat/<Chat GUID>/message",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Get Chat Messages"
  },
  {
    "resource": "chats",
    "methodName": "addParticipant",
    "httpMethod": "POST",
    "path": "/api/v1/chat/<Chat GUID>/participant",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Add Participant to Chat"
  },
  {
    "resource": "chats",
    "methodName": "removeParticipant",
    "httpMethod": "DELETE",
    "path": "/api/v1/chat/<Chat GUID>/participant",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Remove Participant from Chat"
  },
  {
    "resource": "chats",
    "methodName": "read",
    "httpMethod": "POST",
    "path": "/api/v1/chat/<Chat GUID>/read",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Mark Chat as Read"
  },
  {
    "resource": "chats",
    "methodName": "shareContact",
    "httpMethod": "POST",
    "path": "/api/v1/chat/<Chat GUID>/share/contact",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Share Contact Info"
  },
  {
    "resource": "chats",
    "methodName": "contactShareStatus",
    "httpMethod": "GET",
    "path": "/api/v1/chat/<Chat GUID>/share/contact/status",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Get Contact Share Status"
  },
  {
    "resource": "chats",
    "methodName": "typingStart",
    "httpMethod": "POST",
    "path": "/api/v1/chat/<Chat GUID>/typing",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Start Send Typing Indicator"
  },
  {
    "resource": "chats",
    "methodName": "typingStop",
    "httpMethod": "DELETE",
    "path": "/api/v1/chat/<Chat GUID>/typing",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Stop Send Typing Indicator"
  },
  {
    "resource": "chats",
    "methodName": "unread",
    "httpMethod": "POST",
    "path": "/api/v1/chat/<Chat GUID>/unread",
    "pathParams": [
      {
        "paramName": "chatGuid",
        "token": "<Chat GUID>"
      }
    ],
    "summary": "Mark Chat as Unread"
  },
  {
    "resource": "chats",
    "methodName": "count",
    "httpMethod": "GET",
    "path": "/api/v1/chat/count",
    "pathParams": [],
    "summary": "Get Chat Count"
  },
  {
    "resource": "chats",
    "methodName": "create",
    "httpMethod": "POST",
    "path": "/api/v1/chat/new",
    "pathParams": [],
    "summary": "Create New Chat"
  },
  {
    "resource": "chats",
    "methodName": "query",
    "httpMethod": "POST",
    "path": "/api/v1/chat/query",
    "pathParams": [],
    "summary": "Query Chats"
  },
  {
    "resource": "contacts",
    "methodName": "list",
    "httpMethod": "GET",
    "path": "/api/v1/contact",
    "pathParams": [],
    "summary": "Get Contacts"
  },
  {
    "resource": "contacts",
    "methodName": "query",
    "httpMethod": "POST",
    "path": "/api/v1/contact/query",
    "pathParams": [],
    "summary": "Query Contacts"
  },
  {
    "resource": "fcm",
    "methodName": "clientConfig",
    "httpMethod": "GET",
    "path": "/api/v1/fcm/client",
    "pathParams": [],
    "summary": "Get FCM Client Config"
  },
  {
    "resource": "fcm",
    "methodName": "registerDevice",
    "httpMethod": "POST",
    "path": "/api/v1/fcm/device",
    "pathParams": [],
    "summary": "Register Device"
  },
  {
    "resource": "handles",
    "methodName": "get",
    "httpMethod": "GET",
    "path": "/api/v1/handle/<Handle Address>",
    "pathParams": [
      {
        "paramName": "handleAddress",
        "token": "<Handle Address>"
      }
    ],
    "summary": "Get Handle by Address"
  },
  {
    "resource": "handles",
    "methodName": "focusStatus",
    "httpMethod": "GET",
    "path": "/api/v1/handle/<address>/focus",
    "pathParams": [
      {
        "paramName": "address",
        "token": "<address>"
      }
    ],
    "summary": "Get Handle's Focus Status"
  },
  {
    "resource": "handles",
    "methodName": "faceTimeAvailability",
    "httpMethod": "GET",
    "path": "/api/v1/handle/availability/facetime",
    "pathParams": [],
    "summary": "Get FaceTimeAvailability"
  },
  {
    "resource": "handles",
    "methodName": "iMessageAvailability",
    "httpMethod": "GET",
    "path": "/api/v1/handle/availability/imessage",
    "pathParams": [],
    "summary": "Get iMessage Availability"
  },
  {
    "resource": "handles",
    "methodName": "count",
    "httpMethod": "GET",
    "path": "/api/v1/handle/count",
    "pathParams": [],
    "summary": "Get Handle Count"
  },
  {
    "resource": "handles",
    "methodName": "query",
    "httpMethod": "POST",
    "path": "/api/v1/handle/query",
    "pathParams": [],
    "summary": "Query Handles"
  },
  {
    "resource": "icloud",
    "methodName": "updateAlias",
    "httpMethod": "POST",
    "path": "/ap/v1/icloud/account/alias",
    "pathParams": [],
    "summary": "Modify Active Alias"
  },
  {
    "resource": "icloud",
    "methodName": "accountInfo",
    "httpMethod": "GET",
    "path": "/api/v1/icloud/account",
    "pathParams": [],
    "summary": "Get Account Info"
  },
  {
    "resource": "icloud",
    "methodName": "contactCard",
    "httpMethod": "GET",
    "path": "/api/v1/icloud/contact",
    "pathParams": [],
    "summary": "Get Contact Card"
  },
  {
    "resource": "icloud",
    "methodName": "listDevices",
    "httpMethod": "GET",
    "path": "/api/v1/icloud/findmy/devices",
    "pathParams": [],
    "summary": "Get FindMy Devices Locations"
  },
  {
    "resource": "icloud",
    "methodName": "refreshDevices",
    "httpMethod": "POST",
    "path": "/api/v1/icloud/findmy/devices/refresh",
    "pathParams": [],
    "summary": "Refresh FindMy Devices"
  },
  {
    "resource": "icloud",
    "methodName": "listFriends",
    "httpMethod": "GET",
    "path": "/api/v1/icloud/findmy/friends",
    "pathParams": [],
    "summary": "Get FindMy Friends Locations"
  },
  {
    "resource": "icloud",
    "methodName": "refreshFriends",
    "httpMethod": "POST",
    "path": "/api/v1/icloud/findmy/friends/refresh",
    "pathParams": [],
    "summary": "Refresh FindMy Friends"
  },
  {
    "resource": "macos",
    "methodName": "lock",
    "httpMethod": "POST",
    "path": "/api/v1/mac/lock",
    "pathParams": [],
    "summary": "Lock Mac"
  },
  {
    "resource": "messages",
    "methodName": "get",
    "httpMethod": "GET",
    "path": "/api/v1/message/<GUID>",
    "pathParams": [
      {
        "paramName": "guid",
        "token": "<GUID>"
      }
    ],
    "summary": "Get Message by GUID"
  },
  {
    "resource": "messages",
    "methodName": "edit",
    "httpMethod": "POST",
    "path": "/api/v1/message/<GUID>/edit",
    "pathParams": [
      {
        "paramName": "guid",
        "token": "<GUID>"
      }
    ],
    "summary": "Edit Message"
  },
  {
    "resource": "messages",
    "methodName": "embeddedMedia",
    "httpMethod": "GET",
    "path": "/api/v1/message/<GUID>/embedded-media",
    "pathParams": [
      {
        "paramName": "guid",
        "token": "<GUID>"
      }
    ],
    "summary": "Get Message's Embedded Media"
  },
  {
    "resource": "messages",
    "methodName": "notify",
    "httpMethod": "POST",
    "path": "/api/v1/message/<GUID>/notify",
    "pathParams": [
      {
        "paramName": "guid",
        "token": "<GUID>"
      }
    ],
    "summary": "Notify for Silenced Message"
  },
  {
    "resource": "messages",
    "methodName": "unsend",
    "httpMethod": "POST",
    "path": "/api/v1/message/<GUID>/unsend",
    "pathParams": [
      {
        "paramName": "guid",
        "token": "<GUID>"
      }
    ],
    "summary": "Unsend Message"
  },
  {
    "resource": "messages",
    "methodName": "sendAttachment",
    "httpMethod": "POST",
    "path": "/api/v1/message/attachment",
    "pathParams": [],
    "summary": "Send Attachment"
  },
  {
    "resource": "messages",
    "methodName": "count",
    "httpMethod": "GET",
    "path": "/api/v1/message/count",
    "pathParams": [],
    "summary": "Get Updated Message Count"
  },
  {
    "resource": "messages",
    "methodName": "countMe",
    "httpMethod": "GET",
    "path": "/api/v1/message/count/me",
    "pathParams": [],
    "summary": "Get My Sent Message Count"
  },
  {
    "resource": "messages",
    "methodName": "sendMultipart",
    "httpMethod": "POST",
    "path": "/api/v1/message/multipart",
    "pathParams": [],
    "summary": "Send Multipart Message"
  },
  {
    "resource": "messages",
    "methodName": "query",
    "httpMethod": "POST",
    "path": "/api/v1/message/query",
    "pathParams": [],
    "summary": "Query Messages"
  },
  {
    "resource": "messages",
    "methodName": "react",
    "httpMethod": "POST",
    "path": "/api/v1/message/react",
    "pathParams": [],
    "summary": "Send Reaction"
  },
  {
    "resource": "messages",
    "methodName": "listScheduled",
    "httpMethod": "GET",
    "path": "/api/v1/message/schedule",
    "pathParams": [],
    "summary": "Get Scheduled Messages"
  },
  {
    "resource": "messages",
    "methodName": "createScheduled",
    "httpMethod": "POST",
    "path": "/api/v1/message/schedule",
    "pathParams": [],
    "summary": "Schedule a Message"
  },
  {
    "resource": "messages",
    "methodName": "getScheduled",
    "httpMethod": "GET",
    "path": "/api/v1/message/schedule/<ID>",
    "pathParams": [
      {
        "paramName": "id",
        "token": "<ID>"
      }
    ],
    "summary": "Get Scheduled Message by ID"
  },
  {
    "resource": "messages",
    "methodName": "updateScheduled",
    "httpMethod": "PUT",
    "path": "/api/v1/message/schedule/<ID>",
    "pathParams": [
      {
        "paramName": "id",
        "token": "<ID>"
      }
    ],
    "summary": "Update a Scheduled Message by ID"
  },
  {
    "resource": "messages",
    "methodName": "deleteScheduled",
    "httpMethod": "DELETE",
    "path": "/api/v1/message/schedule/<ID>",
    "pathParams": [
      {
        "paramName": "id",
        "token": "<ID>"
      }
    ],
    "summary": "Delete Scheduled Message by ID"
  },
  {
    "resource": "messages",
    "methodName": "sendText",
    "httpMethod": "POST",
    "path": "/api/v1/message/text",
    "pathParams": [],
    "summary": "Send Text"
  },
  {
    "resource": "server",
    "methodName": "ping",
    "httpMethod": "GET",
    "path": "/api/v1/ping",
    "pathParams": [],
    "summary": "Ping"
  },
  {
    "resource": "server",
    "methodName": "listAlerts",
    "httpMethod": "GET",
    "path": "/api/v1/server/alert",
    "pathParams": [],
    "summary": "Get Server Alerts"
  },
  {
    "resource": "server",
    "methodName": "readAlerts",
    "httpMethod": "POST",
    "path": "/api/v1/server/alert/read",
    "pathParams": [],
    "summary": "Mark Alerts As Read"
  },
  {
    "resource": "server",
    "methodName": "info",
    "httpMethod": "GET",
    "path": "/api/v1/server/info",
    "pathParams": [],
    "summary": "Get Server Metadata"
  },
  {
    "resource": "server",
    "methodName": "logs",
    "httpMethod": "GET",
    "path": "/api/v1/server/logs",
    "pathParams": [],
    "summary": "Get Server Logs"
  },
  {
    "resource": "server",
    "methodName": "restartApp",
    "httpMethod": "GET",
    "path": "/api/v1/server/restart/hard",
    "pathParams": [],
    "summary": "Restart Server"
  },
  {
    "resource": "server",
    "methodName": "restartServices",
    "httpMethod": "GET",
    "path": "/api/v1/server/restart/soft",
    "pathParams": [],
    "summary": "Restart Services"
  },
  {
    "resource": "server",
    "methodName": "mediaTotals",
    "httpMethod": "GET",
    "path": "/api/v1/server/statistics/media",
    "pathParams": [],
    "summary": "Get Media Totals"
  },
  {
    "resource": "server",
    "methodName": "mediaTotalsByChat",
    "httpMethod": "GET",
    "path": "/api/v1/server/statistics/media/chat",
    "pathParams": [],
    "summary": "Get Media Totals Per Chat"
  },
  {
    "resource": "server",
    "methodName": "totals",
    "httpMethod": "GET",
    "path": "/api/v1/server/statistics/totals",
    "pathParams": [],
    "summary": "Get iMessage Entity Totals"
  },
  {
    "resource": "server",
    "methodName": "checkUpdate",
    "httpMethod": "GET",
    "path": "/api/v1/server/update/check",
    "pathParams": [],
    "summary": "Check for Server Update"
  },
  {
    "resource": "server",
    "methodName": "installUpdate",
    "httpMethod": "POST",
    "path": "/api/v1/server/update/install",
    "pathParams": [],
    "summary": "Install Server Update"
  },
  {
    "resource": "web",
    "methodName": "landingPage",
    "httpMethod": "GET",
    "path": "/",
    "pathParams": [],
    "summary": "Get Landing Page"
  }
] as const;
